# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
core:
  - changed-files:
      - any-glob-to-any-file:
          - 'README.md'
          - 'pom.xml'
          - '.github/**'
