# The MIT License (MIT)
#
# Copyright (c) 2016-2025 Objectionary.com
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
name: motives
'on':
  push:
    tags:
      - '*'
concurrency:
  group: motives-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motives:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          tag=${{github.ref_name}}
          mkdir -p "gh-pages/${tag}"
          find src/main/resources/org/eolang/motives -name '*.md' -exec cp {} "gh-pages/${tag}" \;
          (
            printf '<html><body style="font-family: monospace;">\n'
            printf '<p>Latest version: %s</p>\n' "${tag}"
            printf '<p>List of lints in this version<p>'
            printf "<ul>\n"
            while IFS= read -r f; do
              n=$(basename "${f}" .md)
              printf '<li><a href="%s">%s</a></li>\n' \
                "/${tag}/${n}.html" "${n}"
            done < <(find "gh-pages/${tag}" -name '*.md')
            printf '</ul>\n'
            printf '<p>Published on %s.</p>\n' "$(date)"
            printf '</body></html>'
          ) > "gh-pages/index.html"

      - uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: gh-pages
          clean: true
